version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: sudo npm install
      - run: sudo npm install -g firebase-tools
      - run: sudo npm install -g @angular/cli
      - run: sudo npm install -g tslint
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: ng build --prod --aot
      - run: './node_modules/.bin/firebase deploy --only hosting --token=$FIREBASE_TOKEN'