version: 2
jobs:
  build:
    branches:
      only:
        - master
      docker:
        - image: circleci/node:12
      working_directory: ~/repo
      steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
        - run: npm install
        - run: npm install --save-dev firebase-tools
        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
        - run: ng build --prod
        - run: './node_modules/.bin/firebase deploy --only hosting --token=$FIREBASE_TOKEN'